language: python
dist: bionic
python:
  - "3.6"      # current default Python on Travis CI
  
# command to install dependencies
install:
  - pip install conan
  - git clone https://github.com/davidtazy/conan-kcov kcov
  - cd kcov
  - conan --version
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan install cmake_installer/3.16.3@conan/stable  -g=virtualenv
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - source activate.sh
  - bash workflow.sh
  - cd ..
  # install deps
  - source kcov/activate.sh
  - mkdir build 
  - cd build
  - conan install .. 
  # build
  - cd build
  - cmake ..
  - cmake --build . --target all

# command to run tests
script:
  - xvfb-run ctest -V
